### ISSUE TITLE
프론트에서 Authorization 헤더를 추출할수 없는 이슈

### ISSUE THREAD

**Issue by FRESH-TUNA** [ghost-coding-king/academy-show#8]
[참고자료](https://letsmakemyselfprogrammer.tistory.com/44)
백엔드에서 CORS설정을 따로 해줘야 프론트에서 받을수 있는것 같습니다.

**Comment by woody-jin** [comment]
Exposed Headers 관련 옵션을 설정하지 않아서 헤더에 담긴 Access Token에 접근하지 못했던 것 같습니다.
해당 옵션 추가하여 코드에 반영했습니다.!
